name: asr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - transformers
  - datasets
  - numpy
  - tqdm
  - ffmpeg
  - av
  - jiwer
  - psycopg2
  - cmake
  - boost
  - eigen
  - pip